# This is a basic workflow to help you get started with Actions

name: test

on:
  pull_request_target:
    paths:
      - '/**' #all codes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #xtract all codes
      - run: npm install & npm run test:ci
